name: Build and Upload Rust Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Rust
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    # Step 3: Build the Rust project in the server folder
    - name: Build Rust project
      run: |
        cd server
        cargo build --release

    # Step 4: Upload the executable as an artifact
    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: server-executable
        path: server/target/release/server