name: Build and Release Rust Executable

on:
  push:
    tags:
      - 'v*'  # Trigger only on version tags (e.g., v1.0, v2.1.3)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Rust
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    # Step 3: Build the Rust project in the server folder
    - name: Build Rust project
      run: |
        cd server
        cargo build --release

    # Step 4: Upload the executable to GitHub Release
    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        assets: server/target/release/server